### ISSUE TITLE
DSM status is 'not installed' after reboot

### ISSUE THREAD

**Issue by wvxx** [fbelavenuto/arpl#52]
As the summary suggests, DSM will install just fine, but as soon as I reboot I am greeted with setup wizard instead of login page. Re-installation never succeeds unless I format the drive completely. That said, it looks like a disposable setup :)

My specs:
Asus ROG Strix H470 mITX
i3-10100
16GB DDR4
Kingston SATA SSD

**Comment by mewallkit** [comment]
I had such a problem as a result of a damaged partition on a usb disk, in order to force the existing installation, I used ssh in the home directory there is a file init.sh,
recommend trying to change the usb drive or the recording method
![image](https://user-images.githubusercontent.com/28947729/180517049-10a0ee63-e00c-4ed1-9c9f-9259fe1d79bb.png)

**Comment by fbelavenuto** [comment]
Alpha stage has many changes, this kind of problem can occur.
